### ISSUE TITLE
User Story 7 Returning User

### ISSUE THREAD

**Issue by monimaj89** [JesseRoss001/loveshop#10]
## User Story 7: Personalized Recommendations for Returning Users with Loyalty Card

As a Returning User with a Loyalty Card

I expect to receive personalized recommendations based on my past purchases

So that it is easier for me to discover relevant Valentine’s day gift ideas.

## Acceptance Criteria:

- [ ] The website uses data from the user’s previous purchases and browsing to suggest Valentine's day products.

### **Priority:**

This is a must-have feature as it not a crucial for website functionality but a nice touch for the user experience.

### **Estimates:**

- Time and effort estimation:

**Comment by enrightc** [comment]
Received by CE.

**Comment by enrightc** [comment]
Reviewers by CE.

**Comment by jamie33o** [comment]
Reviewed by J.O'N
