### ISSUE TITLE
User Story 2 

### ISSUE THREAD

**Issue by JesseRoss001** [JesseRoss001/loveshop#2]
As a potential customer,

I want to read detailed product descriptions, accompanied by  images and reviews,

So that I can make informed decisions regarding my purchase.

### Acceptance Criteria:

- [x] Each product listing includes a description 
- [x]  images showcase the products (additional option to zoom in).
- [x] ratings are prominently displayed.

### Priority:

This is a must-have feature as it directly impacts the user's ability to make informed purchase decisions.

### Estimates:

- Time and effort estimation: Medium

**Comment by enrightc** [comment]
Reviewed by CE.

**Comment by jamie33o** [comment]
reviewed by J.O'N

**Comment by enrightc** [comment]
All acceptance criteria complete.
Although acceptance Criteria 3 it needs some work as it currently displays the rating as a decimal and not a whole number. A separate issue for this has been created.
