### ISSUE TITLE
Color Theme and Font Choices 

### ISSUE THREAD

**Issue by JesseRoss001** [JesseRoss001/loveshop#4]
Secondary Goal after user stories

**Comment by monimaj89** [comment]
I know it is cliche, and probably all projects will be in shades of red, but this is a valentine project so what else could we use? :D I would go with red, shades of pink and maybe some touch of gold to add some luxury and sophistication :D
For a font I would choose something with cursive for headers and their pair for body text:
1. Lovers Quarrel - Cormorant
2. Sacramento - Lato
3. Pacifico - Open Sans
4. Parisienne - Playfair Display
All of them are from Google fonts and look really chic and elegant.

**Comment by monimaj89** [comment]
Sure, but for today I am at work till 11pm, so I will take care of it tomorrow morning.

**Comment by JesseRoss001** [comment]
In the meeting as discussed for tomorrow we have assigned you this task for when you have time

**Comment by monimaj89** [comment]
Yes, I will take care of it first thing in the morning

**Comment by monimaj89** [comment]
![Colour](https://github.com/JesseRoss001/loveshop/assets/117933620/2511ecb5-54ce-4637-b63c-9f6d4b04e695)

**Comment by monimaj89** [comment]
I would go with the white background, black text and pink details, like buttons, borders, hover effects and focus.

**Comment by monimaj89** [comment]
![Zrzut ekranu 2024-02-16 o 09 59 37](https://github.com/JesseRoss001/loveshop/assets/117933620/527c0a8b-dc26-474d-87ba-6afff0aa1757)
![Zrzut ekranu 2024-02-16 o 10 00 46](https://github.com/JesseRoss001/loveshop/assets/117933620/09c7546f-3563-4765-a010-d0e912304c09)

**Comment by monimaj89** [comment]
![Zrzut ekranu 2024-02-16 o 10 03 11](https://github.com/JesseRoss001/loveshop/assets/117933620/34b46489-bc3a-49e9-81ba-bf70f8f16e86)
![Zrzut ekranu 2024-02-16 o 09 59 12](https://github.com/JesseRoss001/loveshop/assets/117933620/94bcc2e5-66c9-4406-8959-812033461137)

**Comment by monimaj89** [comment]
![Zrzut ekranu 2024-02-16 o 10 00 18](https://github.com/JesseRoss001/loveshop/assets/117933620/3f4562f1-a022-49da-a8e4-4eddd6b897fe)
![Zrzut ekranu 2024-02-16 o 10 01 45](https://github.com/JesseRoss001/loveshop/assets/117933620/26916105-f623-462a-ace0-69c518c558a5)

**Comment by JesseRoss001** [comment]
These are great please ensure that these are tested for accessibility . So that people with visual impairments still have access.

**Comment by JesseRoss001** [comment]
Completed
